script_template: inno_setup.iss
app_id: 78A822A8-1E4C-4DAF-A9A8-D798D9A63BFF
app_name: Salmon
publisher_name: SWYWL
publisher_url: https://swywl.com
display_name: 三文鱼
executable_name: Salmon.exe
output_base_file_name: Salmon-Windows-x64-Setup.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: zh
    file: ..\windows\packaging\exe\ChineseSimplified.isl
  - lang: en
privileges_required: admin
